library(tidyverse)
library(stringr)
load(file = "Full_PS1.Robj")


PS1_Artists <- Full_PS1 |>
  select(artistName, Gender, artistBio, artistNationality, Nationality, artistYOB, artistYOD)

PS1_Artists <- PS1_Artists[!duplicated(PS1_Artists), ]  

artist_firstnames <- str_extract(PS1_Artists$artistName, "^\\w+")

# use vectors of male and female names to guess artist gender. a vector of names from the PS1_Artists was put into a genAI model and had it sort names into unambiguous M/F

Mnames <- c(
  "Carl","Jared","Bill","Rudy","Steve","Dieter","Jon","Philip","Richard","Sol",
  "Jeffrey","Gordon","Arthur","Dennis","Robert","Jim","Keith","George","Peter",
  "Clark","Kurt","Stephen","Patrick","Anthony","Lucio","Charles","Fred","Scott",
  "Enrique","Angus","Curt","Brad","Mark","Michael","Forrest","Max","Gary","Italo",
  "Alan","Don","William","Lawrence","Joe","James","Ronald","Dan","Douglas","Ralph",
  "Donald","Joseph","Larry","David","Klaus","Lucas","Mario","Takahiko","Gianfranco",
  "Joost","Ted","Yoshi","John","Andy","Gerard","Tony","Eberhard","Vito","Daniel",
  "Walter","Stefan","Joel","Frank","Ron","Ira","Alain","Bernard","Antoni","Bruce",
  "Doug","Allen","Newton","Lewis","Tim","Geoffrey","Darryl","Tom","Terence","Ernst",
  "Rudolph","Massimo","Emilio","Nicholas","Jake","Pinchas","Leonard","Porfirio",
  "Stewart","Neil","Harvey","Kenneth","Stuart","Craig","Barry","Jack","Roger",
  "Arnold","Brian","Roland","Rolf","Pierre","Gerald","Milton","Alvin","Morton",
  "Malcolm","Ramon","Rafael","Gonzalo","Cletus","Thomas","Ken","Bart","Ishmael",
  "Axel","Christoph","Martin","Julius","Guy","Clayton","Perry","Gregory","Owen",
  "Norman","Vincent","Tadashi","Ladd","Raimund","Rainer","Johan","Rob","Francisco",
  "Aldo","Steven","Cherif","Grégoire","Josef","Markus","Rhys","Roberto","Giovanni",
  "Alighiero","Pier","Luciano","Jannis","Giulio","Pino","Giuseppe","Michelangelo",
  "Gilberto","Adam","Anders","Udo","Willem","Andres","Henri","Hans","Todd","Nathan",
  "Jerome","Ben","Myron","Dean","Howard","Art","Werner","Manuel","Harlan","Kiyoshi",
  "Dirk","Phil","Nigel","Eduardo","Krzysztof","Alexander","Ilya","João","Caetano",
  "Haim","Alberto","Joaquim","Anselmo","Hermano","Nelson","Carlos","Sergio",
  "Glauber","Paulo","Jackson","Julian","Elliott","Calvin","Marc","Stan","Christian",
  "Demetrius","Hank","Herman","Vernon","Clyde","Leroy","Jeff","Rudolf","Otto",
  "Chuck","Ross","Norbert","Peer","Fredrik","Sam","Monty","Andreas","Rod","Franz",
  "Marek","Efrain","Jimmy","Andre","Hugh","Lloyd","Andrew","Russell","Luther",
  "Pablo","Ray","Ivan","Vladimir","Tomas","Yuri","Andrei","Nikolai","Igor","Boris",
  "Evgeny","Dimitri","Aidan","Vadim","Anatoly","Konstantin","Sergei","Heinz",
  "Matthew","Felix","Maciej","Evan","Ulrich","Niko","Rodney","Simon","Oscar","Lars",
  "Jasper","François","Homi","Antony","Raymond","Greg","Henry","Anish","Denis",
  "Roman","Yehuda","Gregor","Denys","Dragan","Slavoj","Rinaldo","Domenico","Nader",
  "Drew","Mike","Kevin","Javier","Shuji","Roddy","Maurizio","Serge","Philippe",
  "Yves","Lothar","Carsten","Geoff","Takashi","Alfredo","Izhar","Luca","Gilbert",
  "Oliver","Matthias","Bob","Eric","Virgil","Olaf","Jorge","Christopher","Sante",
  "Joep","Knut","Masaki","Liam","Gianni","Pieter","Piotr","Nils","Jason","Lincoln",
  "Florian","Timothy","Karsten","Jochen","Wilhelm","Edward","Piero","Cai","Cao",
  "Chen","Chu","Geng","Hong","Hou","Huang","Zhang","Kang","Kum","Li","Long","Ma",
  "Mao","Pan","Qiu","Ren","Tang","Lin","Wang","Liu","Xu","Yan","Yin","Yuan","Danny",
  "Nobuyoshi","Duangrit","Yung","Wong","Zheng","Jin","Tao","Seung","Choi","Arata",
  "Koo","Zhu","Liang","Takeshi","Karl","Rem","Kisho","Navin","Howie","Nicholas",
  "Nicolas", "Avi","Cristian","Isidoro","Toshihiro","Hiroshi","Noritoshi","Jeroen","Kirk",
  "Sanford","Hironori","Jos","Gert","Jay","Matt","Thad","Haluk","Thierry","Omer",
  "Dave","Adel","Ritsaert","Nicolas", "Begona","Gregor","Fynnegan","Jun",
  "Yoon","Mats","Helmut","Anri","Raf","Aleksandr","Oren","Jonathan","Derek","Levi",
  "Cleo","Paige","Molly","Jeremy","Nami","Yasuko","Francis","Heike","Aernout",
  "Santiago","Nedko","Yutaka","Georges","Frédéric","Ahmed","Uzo","Touhami","Samuel",
  "Kendell","Gavin","Isaac","Kaswende","Seydou","Rachid","Moshekwa","Ernest",
  "Zwelethu","Amir","Uche","Antonio","Ibrahim","Yinka","Malick","Lucas","Cecil",
  "Pascal","Noah","Darren","Gilbert","Ulay","Fumimasa","Yasuhiro","Satoru","Motoi",
  "Julian","Winifred","Antoni","Carles","Mateo","Aitor","Fernando","Néstor","Arnulf",
  "Björn","Gerhard","Oswald","Ibon","Meschac","Tomo","Ugo","Ansel","Phillip","Jesse",
  "Nathaniel","Garrett","Graham","Derrick","Kamrooz","Cory","Ronnie","Sean","Bozidar",
  "Marco","Ian","Benjamin","Ernesto","Jose","Tyler","Trenton","Gardar","Brock",
  "Justin","Dionisios","Rico","Can","Jonah","Ignacio","Will","Matthieu","Yoshua",
  "Aaron","Willie","Philipp","Yervant","Remy","Guido","Uwe","Olav","Jacob","Subodh",
  "Guillermo","Serkan","Ola","Jacques","Victor","Niels","Seth","Søren","Jens","Lasse",
  "Henrik","Abel","Ryan","Alessandro","Andrés","Lutz","Kevin","Harry","Roy",
  "Raúl","Diego","José","Brandon","Pedro","Sherko","Ghaith","Sadik","Rasheed","Michel",
  "Fernando","Verne","Ali","Ismail","Ghassan","Tarek","Mohammed","Mahmoud","Jamal",
  "Khalifa","Oday","Yuji","Curtis","Hadi","Rotimi","Luis","Julio","Milford","Avijit",
  "Yusuf","Hiram","Kayode","Andreas","Patrick","Stanley","Nick","Ludwig","Volker",
  "Abe","Johannes", "Merle", "Hilmar", "Bernd", "Kenneth", "Ed", "Royden", "Bernar",
  "Gordon", "Bogdan", "Shigeo", "Emilio", "Herbert", "Sylvano", "Jacques", "Ivor", 
  "Barry", "Harley", "Stephan", "Toshi", "Mauricio", "Wolfram", "Bernhard", "Kip",
  "Imants", "Klaus", "Charlton", "Guglielmo", "Gerald", "Endre", "Edwin", "Darrel",
  "Cham", "Kiyoko", "Win", "Tadeusz", "Yoav", "Alf", "Raquel", "Esti", "Ellsworth",
  "Tyrone", "Livio", "Rea", "Tedeusz", "Wolf", "Gigi", "Mikiya", "Toshio", "Clive",
  "Till", "Imre", "Carroll", "Mimmo", "Yann", "Urlich", "Ansuya", "Geoffrey", "Ante",
  "Dalibor", "Pati", "Starr", "Arch", "Ira", "Edo", "Bomb", "Crash", "Brett", "Dondi",
  "Fab", "Jedd", "Gray", "Bobby", "Curt", "Greer", "Mellissa", "Salvatore", "Ralf",
  "Boyd", "Auste", "Layne", "Theo", "Marcus", "Ion", "Filippo", "Spring", "Dick",
  "Jiro", "Clifford", "Buster", "Bart", "Tseng", "Emery", "Brant",
  "Gaylen", "Maurie", "Earl", "Russ", "Dominick", "Willy", "Warren", "Stan", "Gamal",
  "Guiliano", "Lebbeus", "Jud", "Arman", "Sorel", "Friedrich", "Raffael",
  "Thom", "Tad", "Angelo", "Keiko", "Andras", "Bronson", "Rick", "Russel", "Huck",
  "Babette", "Marcos", "Albert", "Bolivar", "Adalberto", "Anton", "Öyvind", "Mundy",
  "Sherman", "Eldon", "Auturo", "Tadashiko", "Nobue", "Akira", "Yoichiro", "Perry",
  "Guenther", "Julius", "Reynold", "Ahbe", "Biff", "Frantz", "Judge", "Kiely",
  "Nyzda", "Thulani", "Gandy", "Chip", "Marshall", "Muntadas", "Len", "Willard", "Hyman",
  "Leonid", "Toyce", "Shaun", "Siri", "Mekki", "Reese", "Alfred", "Atanacio",
  "Ibsen", "Bert", "Basilios", "Kermit", "Bertram", "Gael", "Sven", "Laszlo", 
  "Bengt", "Les", "Pepón", "Shalom", "Ernie", "Benny", "Woody", "Brooks", "Jantje",
  "Vettor", "Zigi", "Stano", "Gunter", "Ze", "Urban", "Christophe", "Neil", "Ebernard",
  "Rigoberto", "Hirsch", "Fergus", "Gusztáv", "Kaoru", "Sef", "Hermann", "Dermot", 
  "Patricio", "Oswaldo", "Leonardo", "Frans", "Guto", "Eurico", "Ivens", "Christiano",
  "Hélio", "Arnaldo", "Fabio", "Affonso", "Naná", "Sandor", "Ward", "Ludger", "Marin",
  "Simin", "Chung", "Merilyn", "Piotr", "Hunter", "Sturtevant", "Junko", "Sokhi",
  "Karsten", "Leonard", "Clair", "Danny", "Tomie", "Kathe", "Aldert", "Kon", "Giancarlo", 
  "Chiaki", "Jayce", "Noboru", "Vulto", "Ilan", "Péter", "Ryszard", "Jarg", "Ross", "Papo",
  "Truman", "Byron", "Wlodzimierz", "Fabian", "Devon", "Curtis", "Günther", "Rirkrit",
  "Friesenwall", "Heimo", "Helmut", "Stefan", "Claudio", "Hwa", "Dawoud", "Nayland",
  "Taro", "Raphael", "Didier", "Jordan", "Olafur", "Graham", "Henrik", "Lyle", "Jake",
  "Johannes", "Joachim", "Udomsak", "Dinos", "Georg", "Manfred", "Tor", "Erwin", "Hyun",
  "Tobi", "Lawrie", "Shane", "Kasper", "Per", "Miles", "Toland", "Stefano", "Montien",
  "Fabrice", "Kaki", "Kcho", "Dimitris", "Los", "Salem", "Tatsuo", "Olu", "Ricardo", 
  "Guillermo", "Howard", "Gabriel", "Sung", "Charlemagne", "Nic", "Glenn", "Marty", "Rusty",
  "Phillips", "Billy", "Elliot", "Tommy", "Mitchell", "Kenny", "Raul", "Carson", "Ned", 
  "Phill", "Bradley", "Wade", "Riccardo", "Carter", "Laslo", "Milo", "Duncan", "Paul", 
  "Burt"
)

Fnames <- c(
  "JoAnne","Tina","Dawn","Anne","Ruth","Dorothea","Cecile","Nancy","Rosemary",
  "Brenda","Celia","Trisha","Cara","Susan","Sue","Christa","Howardena","Hannah",
  "Agnes","Sylvia","Betty","Edda","Kristen","Colette","Coleen","Julia","Rita",
  "Virginia","Marcia","Judith","Carol","Sally","Jennifer","Suzanne","Mary","Patsy",
  "Judy","Olga","Maryanne","Carmen","Edit","Helen","Donna","Jacqueline","Jana",
  "Vera","Carolynn","Rochelle","Cynthia","Rachel","Beth","Jacki","Connie","Martha",
  "Rosemarie","Jenny","Simone","Constancia","Maureen","Claudia","Joan","Linda",
  "Heidi","Denise","Edith","Jane","Harriet","Lois","Marilyn","Susanna","Ellie",
  "Poppy","Tania","Anita","Mia","Catherine","Natalie","Caroline","Hanne","Marjorie",
  "Johanna","Kathy","Deborah","Carolyn","Cindy","Liz","Wendy","Christina","Birgit",
  "Brigitta","Lenke","Ann","Faith","Peggy","Gina","Lizzie","Delia","Ilona","Ginny",
  "Vickie","Theodora","Barbara","Margaret","Marta","Diane","Lynne","Rebecca",
  "Alison","Pauline","Elaine","Marianne","Dorit","Naomi","Lucy","Risa","Lisa",
  "Vicki","Elisabet","Cathy","Meg","Karen","Tamar","Maria","Eve","Nan","Sharon",
  "Brigitte","Antje","Monika","Anette","Yana","Sofia","Annie","Constance","Paula",
  "Sophie","Gayle","Viveca","Bobbi","Cheri","Sonya","Phyllis","Allyson","Dona",
  "Hatty","Zarina","Kristina","Kristin","Inghild","Irene","Silvie","Meret","Annea",
  "Margarita","Marisa","Stephanie","Eva","Francoise","Audrey","Eleni","Priscilla",
  "Emma","Camille","Vivian","Eleta","Nanette","Nadine","Gladys","Maren","Janet",
  "Fern","Sandra","Mavis","Shirley","Kaylynn","Shelley","Marylin","Wenda",
  "Philomena","Aimee","Ethyl","Valeria","Ksenija","Judite","Kate","Madeleine",
  "Kathleen","Annette","Lorna","Pam","Emily","Christine","Holly","Bette","Mira",
  "Debra","Jessica","Ana","Beverly","Buffy","Janis","Fiona","Sabina","Amy",
  "Andrea","Katharine","Margo","Victoria","Helene","Gretchen","Eilis","Sonja",
  "Diedre","Zeena","Alva","Betsy","Eleanor","Kiki","Renée","Maura","Grace","Miriam",
  "Shirin","Diosa","Mimi","Yvonne","Beyhan","Elyn","Elena","Larisa","Karin","Else",
  "Sissel","Wijnanda","Shelagh","Deirdre","Jeanette","Rose","Rini","Inez","Bettina",
  "Merce","Sylvie","Angela","Christiane","Andree","Verushka","Marina","Lena",
  "Oxana","Mila","Julie","Cheryl","Mari","Phoebe","Patricia","Laura","Paola",
  "Iris","Bina","Jocelyn","Cecilie","Yoshiko","Martine","Vanessa","Sadie",
  "Véronique","Ami","Vidya","Fariba","Sarah","Leah","Sabine","Finola","Sukey",
  "Hiromi","Lucia","Heidrun","Isa","Laurinda","Josephine","Ikue","Mariko","Maggie",
  "Jorunn","Carrie","Momoyo","Charlotta","Jenny","Dana","Hannelore","Hanne","Vera",
  "Aglaia","Louise","Maki","Hanayo","Adria","Bruna","Teresa","Cecily","Maud",
  "Siobhan","Frances","Elizabeth","Daphne","Janie", "Amie","Vaimarama","Janie","Laura",
  "Maria","Liesbeth","Sabine","Elke","Claudia", "Julia","Paola","Montserrat","Mary",
  "Fiona","Sara","Elizabeth","Martha","Cathy", "Christy","Naomi","Elisabetta",
  "Rosa","Ellen","Emily","Norma","Susan","Lina",
  "Rineke","Donna","Krizia","Sarah","Cady","Catherine","Penelope","Rosemarie",
  "Luciana","Karen","Caitlin","Amy","Margaret","Molly","Judith","Jill","Despina",
  "Marina","Jane","Ghada","Georgina","Zarina","Angelika","Begona","Susanne","Sue",
  "Eleanor","Katrin","Hope","Anissa","Pipilotti","Mika","Chiharu","Yuriko","Kaori",
  "Nene","Kathryn","Ana","Pilar","Tania","Carmela","Alicia","Priscilla","Cristina",
  "Eulalia","Vera","Ingrid","Sachiko","Tatjana","Stefania","Oksun","Ulrike","Niamh",
  "Cecilia","Mimi","Sherrie","Carrie","Nina","Olivia","Kristin","Rina","Tamy",
  "Tanyth","Huma","Carol","Sarah","Bethany","Angela","Michelle","Chie","Esra",
  "Andreja","Nira","Ingrid","Jude","Vija","Sharon","Gunilla","Yoko","Cornelia",
  "Zoë","Shinique","Stephanie","Ai","Jaishri","Nancy","Sophie","Vandana","Marie",
  "Caroline","Dorota","Joanna","Nicole","Joyce","Magdalena","Carla","Chantal",
  "Helena","Ann","Lynda","Sheila","Assia","Lili","Theresa","Kirsten","Lea","Monica",
  "Nasreen","Tellervo","Tea","Anni","Stiina","Salla","Joy","Corita","Yvonne",
  "Cheryl","Heather","Melanie","Tauba","Trisha","Kerstin","Margaret","Mary","Leidy",
  "LaToya","Tamar","Vlatka","Alisha","Deana","Leigh","Dani","Sonia","Tala","Liz",
  "Hanna","Steina","Diane","Janet","Shannon","Lara","Jane","Maureen","Jayne",
  "Suzanne","Virginia","Marie","Elizabeth","Samella","Senga","Betye","Ruth","Julie",
  "Franziska","Carina","Lauren","Fia","Gina","Gelsey","Lizzie","Liene","Vivienne",
  "Loretta","Kelly","Kristy","Silvia","Jennifer","Yayoi","Allison","Akane","Oana",
  "Jananne","Afifa","Monira","Layla","Thuraya","Wafaa","Alia","Mona","Rachel",
  "Hanaa","Nuha","Katy","Nadia","Diane","Kristi","Dolores","Doreen","Emilie","Ilka",
  "Steffani","Athena","Carolyn","Servane","Tammy","Shelley","Paulina","Raha",
  "Lachell","Danielle","Niloufar","Becky","Jeanne","Amina","Gianna","Karimah","Miho",
  "Klara","Selma","Emilija","Monika","Rosalyn","Marisol", "Francine", "Mollyne", 
  "Dove", "Senta", "Diana", "Gwenn", "Norie", "Charlotte", "Danae", "Dena", "Pola",
  "Alice", "Kit", "Mirit", "Connie", "Katherine", "Heide", "Elaine", "Christiana",
  "Francene", "Cathy", "Lisa", "Joan", "Liz", "Martine", "Frances", "Dana", "Mimi",
  "Marina", "Brigid", "Catherina", "Jennifer", "Amy", "Marilyn", "Barbara", "Athena",
  "Gloria", "Cheryl", "Joy", "Nancy", "Mary", "Silvia", "Sondra", "Judy", "Nina", 
  "Ellen", "Edie", "Roberta", "Patty", "Dominique", "Shirley", "Lydia", "Liliana",
  "Sheila", "Stephanie", "Christine", "Aggie", "Aura", "Marcia", "Patricia", "Alexa",
  "Terry", "Jane", "Daisy", "Dina", "Sharon", "Carol", "Vered", "Marilla", "Susan",
  "Randal", "Takako", "Salomé", "Leora", "Betsy", "Ethel", "Eunice", "Esther", 
  "Lucy", "Jackie", "Meredith", "Micki", "Venerina", "Sophi", "Rosalind", "Katie",
  "Marytha", "Helaine", "Evelyn", "Janey", "Grace", "Rhonda", "Corinne", "Regina",
  "Anita", "Debbie", "Bonnie", "Denise", "Georgia", "Cara", "Eileen", "Jeanne", 
  "Sandy", "Fran", "Lyn", "Diane", "Ariane", "Therese", "Debby", "Joanne", "Candace",
  "Martha", "Julia", "Izzy", "Elisa", "Ruby", "Jo", "Roberta", "Vibeke", "Zita", 
  "Jolene", "Naomi", "Clarissa", "Maryanne", "Stacey", "Victoria", "Marie", "Suzan",
  "Francoise", "Luisa", "Malinda", "Margarita", "Dorothy", "Melissa", "Laura", "Therese", 
  "Patti", "Yvonne", "Eugenia", "Freya", "Cathey", "Isabella", "Abigail", "Juliette", "Julie", 
  "Judie", "Dannielle", "Kim", "Madeline", "June", "Elsa", "Maude", "Daria", "Marsha", "Bettsy", 
  "Barbra", "Gail", "Laurie", "Michele", "Dianne", "Hilary"
)

PS1_Artists <- PS1_Artists |>
  mutate(Gender = case_when(
    str_extract(PS1_Artists$artistName, "^\\w+") %in% Mnames ~ "male", 
    str_extract(PS1_Artists$artistName, "^\\w+") %in% Fnames ~ "female",
    Gender == "" ~ NA, 
    
    TRUE ~ Gender
  ))

write.csv(PS1_Artists, "PS1_Artists.csv", row.names = FALSE)

save(PS1_Artists, file = "PS1_Artists.Robj")

Full_PS1 <- Full_PS1 |>
  mutate(Gender = case_when(
    str_extract(Full_PS1$artistName, "^\\w+") %in% Mnames ~ "male", 
    str_extract(Full_PS1$artistName, "^\\w+") %in% Fnames ~ "female",
    Gender == "" ~ NA, 
    
    TRUE ~ Gender
  )) |>
  select(-"Nationality")

###### adding 'likelihood' to names not already assigned ######

# using multiple bots to categorize into likelihood of M/F then take the average:

# bot 1

point01 <- c("Lee Breuer","Jean Dupuy","Willoughby Sharp","Ralston Farina","Evriah Bader",
             "Milet Andrejevic","Jan Hafström","Skip La Plante","Amado Aldaraca",
             "Licio Isolani","Gilles Larrain","Jerry Clapsaddle","Zadik Zadikian",
             "Manny Farber","Caspar Henselmann","Kent Floeter","Lou Forgione",
             "Lowell Cross","Jerry McMillan","Gene Tyranny","Morgan Fisher",
             "Noel Harding","Jaime Ardila","Al Robbins","Jean Mauboules",
             "Koki Doktori","Gerrit Henry","Rene Ricard","Krijn Giezen",
             "Toby MacLennan","Gerd Rohling","Cosimo Di Leo Ricatto",
             "Erland Cullberg","Enno Hallek","Bo Trankell","Petter Zennstrom",
             "Reinhard Niedermeier","Henk Visch","Louis Hock","Jost Markgraf",
             "Rocco Di Pietro","Lee Roy Champagne","Al Honig","Bryan Rogers",
             "Kes Zapkus","Jean Charles Blanc","Jan van den Dobbelsteen",
             "Chihung Yang","Jean Otth","Camus Celli","Blaylock Peppard",
             "Christiaan Bastiaans","Chris Brown","Scot Gresham-Lancaster",
             "Franklin Schaffner","Alex Locadia","Tatsumi Orimoto",
             "Franc Palaia","Dale Wilhelm","Nicolai Ovchinnikov",
             "Min Tanaka","Milovan Markovic","Kavin Buck","Fedo Ertl",
             "Jean Dupuy","Jan Hoet","Joad Raymond","Mat Collishaw",
             "Richie Hawtin","Chris Hoover","Claude Léveque",
             "René Santos","Alexis Rockman","Jan Baracz","Luke Roberts",
             "Aby Warburg","Edgar Martins","Ry Rocklen","Dread Scott",
             "Zak Kitnick","Lee Isaac Chung","Brody Condon","Debo Eilers",
             "Franklin Evans","Bruno Jakob","Tan Lin","Saul Melman",
             "Rashaad Newsome","Conrad Ventur","Harold Mendez",
             "Edgardo Aragón","Ilja Karilampi","Ulysses Jenkins",
             "Tyrus Wong","Charlie Ahearn","Wes McGee","Mecky Reuss",
             "Himat M. Ali","Dia al-Azzawi","Hiwa K","Rafa Nasiri",
             "Aki Onda","Zhou Tao","He Xiangyu","Saul Ostrow",
             "Chris Jonic","Louis Grenier","Gerry Griffen",
             "Alec Bernstein","Charlie Morrow","Marcel Dot",
             "Radford Thomas","Wolfgang Luy","Wayne Hazen", "Noel Harding",
             "Wolfgang Mally","Al Calderaro","Dale Frank", 
             "Harald Klingelhöller","Gerd Rohling","Jean Dupuy","Louis Grenier",
             "Toby MacLennan","Gerry Morehead","Kent Shell","Christof Kohlhöfer",
             "Willi Smith","Louis Chacallis","Kees de Goede","Ter Hell",
             "Francois Martin","Klause Schmitt","Gustavo Ojeda","Saul Ostrow",
             "Standish Lawder","Allan Wexler","Spencer Holst","Alejandro Arango",
             "Ingo Günther","Jan van den Dobbelsteen","R.T. Livingston",
             "Rene Daniels","Louis Renzoni","Jean-Luc Poivret","Bruno Ehrs",
             "Chris Strachwitz","Emmanuel Pereire","Wes Jones","Chris Scholz",
             "Bolek Greczynski","Mel Rosenthal","Christiaan Bastiaans",
             "Jean-Luc Vilmouth","Adir Sodre","Mel Ziegler","Mat Collishaw",
             "Olivier Ferrieux","Reiner Goerss","Alexis Rockman",
             "Juan Galdeano","Celeste Boursier-Mougenot","Beat Huber",
             "Aidas Bareikis","Lionel Esteve","Petteri Nisunen","Marko Peljhan",
             "Vincente Razo","Chris Sauter","Colin Beatty","Hubert Duprat",
             "Jussi Heikkila","Vincenzo Agnetti","Tano Festa","Francesco Lo Savio",
             "Remo Salvadori","Ettore Spalletti","Franco Vaccari","Eike Becker",
             "Jürgen Frisch","Jimbo Blachly","Ethan Crenson","Bertrand Lavier",
             "Luigi Ontani","Muhal Abrams","Chris Cutler","Tod Dockstader",
             "Yamataka Eye","Keenan Lawler","Arto Lindsay","Lou Reed",
             "Ryuichi Sakamoto","Steinski","Loudon Wainwright","Tehching Hsieh",
             "Winsor McCay","Joshua Davis","Alex Galloway","Sebastian Luetergt",
             "Carlo Zanni","Gim Hongsok","Bruno Peinado","Dario Solman",
             "Gustavo Artigas","Miguel Calderon","Wayne Guyton",
             "Declan Clarke","Jongku Kim","Jean-Francois Moriceau",
             "Katsuhiro Saiki","Erik Hanson","Wayne Gonzales","Chris Martin",
             "Ohad Meromi","Ricky Sears","Louis Cameron","Nico Krebs",
             "Taiyo Onorato","Andisheh Avini","Kent Henricksen",
             "Geof Oppenheimer","Devendra Banhart","Corey D'Augustine",
             "Luke Fowler","Saul Levine","Maury Colton III","Ari Marcopoulos",
             "Francesco Vezzoli","Eyal Danieli","Radcliffe Bailey",
             "Dario Robleto","Zak Kitnick","Chris Wiley",
             "Khalid Al Gharaballi","Abdullah Al-Mutairi","Barrak Alzaid",
             "Zhao Zhao","Harald Thys","Reginald Dwayne Betts",
             "Conor Broderick","Halim Flowers","Ojore Lutalo",
             "Welmon Sharlhorne","Zadik Zadikian","G.H. Hovagimyan",
             "Sandro Martini","Jan Yoors","Frederick Spratt","Henk Visch",
             "Erik Steinbrecher","Zilvinas Kempinas","Jeppe Hein",
             "Manny Farber","Xavier Le Roy","Deng Tai","Reza Abdoh",
             "Magnus Wibom","Chris Yuin","Melvin Charney","Adrian Scott",
             "Morgan Fisher","Noriyuki Haraguchi","Franky Kong",
             "Hedi Slimane","Johnston Foster","Loris Cecchini",
             "Abbas Kiarostami","Kris Martin","Leandro Ehrlich",
             "Alejandro Jodorowsky","Umar Rashid","Julien Ceccaldi")

point21 <- c("Kendall Shaw","Alex Kayser","Morgan Thomas",
             "Addison Parks","Kai Eric","Toby Old","Nat Dean",
             "Pops Cooper","Q.J. Stephenson","Mo Bahc","Ho Yoo Choi",
             "Bing Lee","Taeho Lee","Ming Mu-Ray","Georgii Kizevalter",
             "Berhard Sachs","Tone E. Ch. Johansen","Iskender Yediler",
             "Cannon Hudson","Eckhard Etzold","Job Koelewyn",
             "Sang-Gyel Oh","J. Morgan Puett","Fang Tu","Fang Weiwen",
             "Ho Siu-kee","Shu-Min Lin","Shu Qun","Song Yonghong",
             "Song Yongping","Su Xinping","Tsong Pu","Wen Pulin",
             "Wu Shan Zhuan","Wu Tien-chang","Sumset Jumsai",
             "Kiyonori Kikutake","Jinai Kim","Surasi Kusolwong",
             "Tsuyoshi Ozawa","Liadin Cooke","Mo White","Beck Underwood",
             "Chin-wai Ching","Oladélé Bamgboyé","Gebre Kristos Desta",
             "Erhabor Emokpae","Dumile Feni","Kay Hassan",
             "Sydney Kumalo","Iba N'Diaye","Tshibumba",
             "Robin Bruch","Costa","Robin Lee Crutchfield","M. Demuro",
             "A. Kynn Forgach","C.J Collins","Sur Rodney (Sur)",
             "Yee Jan Bao","Toyko Hirata","Johnie Hugh Horn","Madison Bell",
             "H. D.","Robin Utterback","A. Leroy","Nanue Lelue",
             "Alejandro Sina","Colin Chase","Merrin Eirth","Cameron McNall",
             "B. Wurtz","Sérgio Bernardes","Liadin Cooke","L. Brandon Krall",
             "Robin Stanaway","Rene Pierre Allain","Harold Baumbach",
             "Spencer Gregory","Ik-Joong Kang","L.C. Armstrong",
             "Ange Leccia","Glen Seator","Xinping Wang","Du Wang",
             "Arrow Mueller","Jovi Schnell","Gibb Slife","Jan Harrison",
             "Nicola De Maria","Amedeo Martegani","Safy Etiel",
             "E.F. Costa","Chris Bors","Akshay Desai","Manabu Inada",
             "Panajotis Mihalatos","Karlis Rekevics","Augusto Arbizo",
             "Antoine Berghs","Yun-Fe Jin-Hua","Jérôme Basserode",
             "Bartolomeu dos Santos","Darinka","Tomislav Buntak",
             "Kristian Kožul","8gg","Wensheng Dong","Hu Jieming",
             "Songhua Li","Yongfeng Ma","Tan Xu")

point51 <- c("Mabou Mines","Centre for Experimental Art and Communication",
             "S.E.M. Ensemble","Disband","Archizoom Associati","Grupo UFO",
             "AMMO","Church of the Subgenius","Krononauts","Strange Party",
             "Die Tödliche Doris","Teufelbergproduktion",
             "Survival Research Laboratories","Fast Forward","Queens Symphony Orchestra",
             "Ant Farm","Haus-Rucker-Co","Venturi, Rauch and Scott Brown",
             "Red Square Design","Stiletto","Lascari","Medical Hermeneutics",
             "The Peppers","Even Bie-Larsen","IRWIN","Blacklips Performance Cult",
             "P.O.N.Y.","Diabologum","Encore","Maison Martin Margiela",
             "Gran Fury","AMA","DJ Spooky","Kunstlabor","Mutamussik",
             "Stereolab","Fluxus","New Analysis Group","Southern Artists Salon",
             "2dk: David d'Heilly & Kayoko Ota","Edge: Michael Chan & Gary Chang",
             "Buero Friedrich","Herzog & de Meuron, Basel","Low-Flame",
             "The Butoh Rockettes","Granular Synthesis","Avirex","Burberry",
             "Comme des Garçons","Dolce & Gabbana","Gucci","Prada",
             "Rayban-Luxottica","Stone island","Valentino","Thinkdance",
             "My Barbarian","Primary Information","Superstudio",
             "The Bruce High Quality Foundation","Grand Openings",
             "CONFETTISYSTEM","Office for Political Innovation",
             "ECKHAUS LATTA","fierce pussy","Escobedo Soliz Studio",
             "Dream the Combine","FreelandBuck","OFICINAA",
             "Low Design Office (LOWDO)","Matter Design",
             "Deep Dish TV", "BlackMass Publishing",
             "Las Nietas de Nonó","POOL (Performance On One Leg)",
             "Coach House Press","Nelvana Limited","N.E Thing Co. Ltd.",
             "La Groupe des Beaux Arts","Friday Architects","Video Zagreb","DNA",
             "Futura 2000","Firelight","Irva", "Squat Theater","TODT","Fluxus","Future Tents","NASA",
             "Videofreex","WGBH-TV: Independent Video","Casa Nicaragua",
             "Cispes","Siggraph '83","Exchange T.V.","Paper Tiger Television",
             "Radio Venceremos","Raindance Foundation","A Touch of Class",
             "Double Dutch Dancers","Lizard","Hawaii Art and Energy, Inc.",
             "Pacific Street Film Collective","Channel Four Television",
             "Crew of Battlefields Project","K.O.S. (Kids of Survival)",
             "Empire State Photographers","Information Fiction Publicite (IFP)",
             "Samba School of San Miguel","A.T.W.","Screammachine",
             "The Rivington School","Y-Space","Actress","FAT magazine",
             "Sincerely Yours Escorts","Standard and Poor","The Stand",
             "Up & Co","WFMU","zingmagazine","Kyupi Kyupi","Group Material",
             "Chop Shop","Chris & Cosey","Cibo Matto","Fischerspooner",
             "Impossible Music","I-Sound","The Residents","Sonic Youth",
             "The Art Guys","Ages 5 & Up","Exonemo","Groovisions",
             "Nihon-Ishina","Stereotype Produkts","TGV","Tugboat",
             "Tycoon Graphics","Basicray","JODI","Minus Space","Base",
             "The Bruce High Quality Foundation","Guerrilla Art Action Group",
             "Harvard University Graduate School of Design","GCC",
             "ACT UP, New York","Pussy Riot","The Radek Community","Voina",
             "MSHR","American Artist","GisMo (Jessica Gispert and Crystal Pearl Molinary)",
             "Standing On The Corner","Mabou Mines","Queens Symphony Orchestra",
             "IRWIN","Gelatin","Dearraindrop","OBRA Architects",
             "Ball-Nogues Studio","WORK Architecture Company","MOS Architects",
             "Performa 09","CODA","The Living","Karrabing Film Collective",
             "Apple Brass Quintet","Akademia Ruchu","SHoP Architects PC",
             "ROY","Solid Objectives-Idenburg Liu","HWKN Hollwich Kushner",
             "For Freedoms","Warchurch (Skech185 and Analog[ue] Tape Dispenser)",
             "BFFA3AE")

point81 <- c("Dee Shapiro","Bobbie Oliver","Laurace James","Hass Murphy",
             "Frankie Mann","Rae Berolzheimer","Blondell Cummings",
             "Pooh Kaye","Didi Dubelyew","Leslie Lalehzar",
             "Pat Walsh","Tere O'Connor","Robin Klingensmith",
             "Lynn Swanson","Jean Champagne","M.L. Heivly",
             "E.F. Higgins","Pat Tavenner","Robin Holder","Frankie Mann",
             "Jessie Benton-Evans-Gray","Katrini Krinsky","Rhea Sanders",
             "Katheryn Anne Sins", "Jean Gallagher","Adrienne Farb","Roxanne Blanchard",
             "Rise Cale","Edy Ferguson","Liza May Post","Clara Williams",
             "Nikki Lee","Tamara Grcic","Tracey Baran","Lucky DeBellevue",
             "Adrianna Sa","Fassih Keiso","Yang Lian","Munro Galloway",
             "Valerie Prot","Amanda Ralph","Katleen Vermeir","Wayne Gonzales",
             "Cannon Hudson","Chris Martin","Xiuwen Cui","Felisa Funes",
             "Meredyth Sparks","Amanda Fielding","Valborg Fletre Linn")

onepoint01 <- c("Robin Lehrer", "Gillian Bradshaw-Smith","Elizebeth Egbert","Vita Giorgi",
                "Madelon Jones","Arlene Slavin","Ilise Greenstein",
                "Clover Vail","Merrill Wagner","Tracey Berg",
                "Chi Chi Valenti","Miss Ming Vauze","Helina Hughes",
                "Cookie Mueller","Rii Kanzaki","Tomiyo Sasaki",
                "Birgitta Liljebladh","Lyne Lapointe","Danita Geltner",
                "Leslie-Jane Pessemier","Marion Gray","Rae Langston",
                "Su Friedrich","Chick Strand","Ame Gilbert",
                "Catti (Catherine James)","Lynn Klosky","C. Ann Carter",
                "Leni Andrade","Gal Costa","Rhody Streeter",
                "Su-Chen Hung","Chieo Senzaki","Pene Bonita",
                "Bisa Washington","Leslie Sharpe","Lynn McCary",
                "Hannan Ashrawi","Luce Irigaray","Suse Eichinger",
                "Alix Lambert","Valérie Pigato","Joke Robaard",
                "Jody Culkin","Aki Fujiyoshi","Kerry Mullett",
                "Zvezdana Rogic","Ute Weiss-Leder","Wu Mali",
                "Itsuko Hasegawa","Anna Gabriel","Claude Wampler",
                "Jody Sperling","Marijke van Warmerdam",
                "Wynne Greenwood","Aki Sasamoto","Genesis P-Orridge",
                "Sister Karen Boccalero","Korakrit Arunanondchai (ambiguous but leaning female? leave if needed)",
                "Dora Budor","Tolia Astakhishvili","Geumhyung Jeong",
                "Ser Serpas","Pat Oleszko","Pat Ivers","May Wilson",
                "Candida Alvarez","Jamillah Jennings","Francesca Jones",
                "Avital Oz","Anna Conway","Anna Craycoft",
                "Gioia Timpanelli","Inge Mahn","Alba Cane","Dee Axelrod",
                "Lilly Brody","Jody Culkin","Tonie Roos","Isolde Wawrin",
                "Avital Oz","Paulette Nenner","Pooh Kaye","Pat Place",
                "Robin Tewes","Anna Bisso","Jeanie Black","Marlene Bloomer",
                "Leslie Eve Child","Catti (Catherine James)","Kris Waneck",
                "Maz Brook","Rii Kanzaki","Lynn Swanson","Kieko Bonk",
                "Ame Gilbert","Jessie Benton-Evans-Gray","Pene Bonita",
                "Josely Carvalho","Sydney Blum","Danita Geltner","Toni Morrison",
                "Tomiyo Sasaki","Tuija Lindstrom","Merian Soto",
                "Katrini Krinsky","Janice Becker","Toby Buonagurio",
                "Faithanne Carapella","Ora Lerman","Sabra Moore",
                "Vernita Nemec","Rhea Sanders","Selina Trieff","Suruchi Chand",
                "Jean Gallagher","Renee Rockoff","Muna Tseng","Adrienne Farb",
                "Jerri Allyn","Mierle Laderman Ukeles","Lori Beth Blaikie",
                "Penny Coleman","Moira Sina","Robyn Almaleh","Margot Lovejoy",
                "Serena Bocchino","Geraldine Erman","Anna Mariani",
                "Roxanne Blanchard","Mirjam de Zeeuw","Polly Kiesel",
                "Lynn Robinson","Camilla Warenskjold-Dybvik","Antonella Piemontese",
                "Daina Shobrys","Esperanza Cortes","Kay Miller","Solfrid Mortensen",
                "Lynn Wilder","Anna Plotnicka","Andromahi Kefalos",
                "Hillary Leone","Katharina Karrenberg","Dara Silverman",
                "Tatyana Gubash","Buffie Johnson","Margrit Lewczuk",
                "Yvette Helin","Zaporah Jacobs","Lanie Lee","Marijke van Warmerdam",
                "Candida Alvarez","Gunda Foerster","Ursula Kraft",
                "Liza May Post","Juana Valdes","Clara Williams",
                "Mandy Ming-Yin Yim","Fabiana de Barros","Juliet Lea",
                "Rekha Rodwittiya","Alma Suljevic","Adriana Varejão",
                "Ciara Finnegan","Jean van Heeswijk","Danica Phelps",
                "Tomoko Takahashi","Fatimah Tuggar","Kaisu Koivisto",
                "Tamara Grcic","Raffaella Nappo","Sabrina Mezzagui",
                "Adriana Arenas","Tracey Baran","Chakaia Booker",
                "Alix Lambert","Jyung Mee Park","Carola Dertnig",
                "Ivana Franke","Midori Araki","Hanako Kunishi",
                "Hitomi Uchikura","Yuka Wake","Amanda Forbis",
                "Alexandra Korejwo","Liane Lang","Lucretia Knapp",
                "Eline McGeorge","Jeanine Oleson","Jessie Shefrin",
                "Ottonella Mocellin","Valerie Prot","Amanda Ralph",
                "Constanze Schweiger","Katleen Vermeir","Shoshana Dentz",
                "Cadence Giersbach","Leemour Pelli","Julianne Swartz",
                "Petra Lindholm","Dianna Frid","Kira Lynn Harris",
                "Xiuwen Cui","Sungmi Lee","Lisi Raskin","Felisa Funes",
                "Meredyth Sparks","Senam Okudzeto","Margie Strosser",
                "Tamara Gonzales","Prema Murthy","Amalia Mesa-Bains",
                "Shizuka Yokomizo","Carey Young","Vinca Kruk",
                "Sophia Al Maria","Fatima Al Qadiri","Amal Khalaf",
                "Samara Golden","Amal Kenawy","Jillian Mayer",
                "Carole Alden","Tameca Cole","Amber Rose Daniel",
                "Nereida García-Ferraz","Chandra McCormick",
                "Rowan Renee","Treacy Ziegler","Elysia Chuquimia Crampton",
                "Charisse Pearlina Weston","Glenda Hydler","Yeohlee Teng",
                "Kei Takei","Su-Mei Tse","Katrín Sigurdardóttir",
                "Rania Stephan","Saya Woolfalk","Frieda Toranzo Jaeger",
                "Whitney Claflin","Amanda Fielding","Valborg Fletre Linn",
                "Yoshie Ueki","Anna Oppermann","Miri Segal","Aïda Ruilova",
                "Libby McInnis","Isca Greenfield-Sanders","Misaki Kawai",
                "Zackary Drucker","Motandi Ouoba","Sascha Braunig",
                "Iiu Susiraja","Leslie Martinez","Jasmine Gregory",
                "Guerrilla Girls")


Full_PS1 <- Full_PS1 |>
  mutate(GenderConf1 = case_when(
    Gender == "female" ~ 1,
    Gender == "male" ~ 0, 
    Full_PS1$artistName %in%  point01 ~ 0,
    Full_PS1$artistName %in%  point21 ~ 0.2,
    Full_PS1$artistName %in%  point51 ~ 0.5,
    Full_PS1$artistName %in%  point81 ~ 0.8,
    Full_PS1$artistName %in%  onepoint01 ~ 1, 
    TRUE ~ 0.5
  ))


# bot 2

point02 <- c("Lee Breuer", "Jean Dupuy", "Willoughby Sharp", "Milet Andrejevic",
             "Skip La Plante", "Amado Aldaraca", "Licio Isolani", "Gilles Larrain",
             "Jerry Clapsaddle", "Kendall Shaw", "Zadik Zadikian", "Manny Farber",
             "Caspar Henselmann", "Kent Floeter", "Lou Forgione", "Lowell Cross",
             "Alex Kayser", "Jerry McMillan", "Gene Tyranny", "Noel Harding", 
             "Jaime Ardila", "Al Robbins", "A. David Christian", "Jean Mauboules",
             "Koki Doktori", "Addison Parks", "Gerrit Henry", "Rene Ricard", 
             "Krijn Giezen", "Gerd Rohling", "Cosimo Di Leo Ricatto", "Erland Cullberg",
             "Enno Hallek", "Bo Trankell", "Petter Zennstrom", "Louis Chacallis", 
             "Ter Hell", "Reinhard Niedermeier", "Henk Visch", "Louis Hock", 
             "Toby Old", "Jost Markgraf", "Rocco Di Pietro", "Lee Roy Champagne",
             "Al Honig", "Bryan Rogers", "Kes Zapkus", "Jean Charles Blanc", 
             "Jan van den Dobbelsteen", "Troyan Tecau", "Jean Otth", "Camus Celli", 
             "Bucky Schwartz", "Daryl Trivieri", "Christiaan Bastiaans", "Tere O'Connor", 
             "Chris Brown", "Scot Gresham-Lancaster", "Laurence Postma", 
             "Standish Lawder", "Franklin Schaffner", "Rhody Streeter", "Pops Cooper",
             "Tatsumi Orimoto", "Mo Bahc", "Ho Yoo Choi", "Jean Patrick Icart-Pierre",
             "Taeho Lee", "Franc Palaia", "Georgii Kizevalter", "Nicolai Ovchinnikov",
             "Vitas Stasunas", "Min Tanaka", "Milovan Markovic", "Even Bie-Larsen",
             "Kavin Buck", "Chisen Furukawa", "Fedo Ertl", "Jan Hoet", 
             "Jean-Marc Lévy-Leblond", "Joad Raymond", "Berhard Sachs", "Mat Collishaw",
             "Jean-Rene de Fleurieu", "Richie Hawtin", "Chris Hoover", 
             "Claude Lévêque", "René Santos", "Måns Wrange", "Iskender Yediler",
             "Alexis Rockman", "Jan Baracz", "DJ Spooky", "Cannon Hudson", 
             "Eckhard Etzold", "Job Koelewyn", "Sang-Gyel Oh", "Luke Roberts", 
             "Aby Warburg", "Fang Tu", "Fang Weiwen", "Ho Siu-kee", "Shu Qun", 
             "Song Yonghong", "Song Yongping", "Su Xinping", "To Weun", "Tsong Pu", 
             "Wen Pulin", "Wu Shan Zhuan", "Wu Tien-chang", "Sumset Jumsai", 
             "Chitti Kasemkitvana", "Kiyonori Kikutake", "Surasi Kusolwong", 
             "Andar Manik", "Tsuyoshi Ozawa", "Jan Kopp", "Chin-wai Ching", 
             "Oladélé Bamgboyé", "Gebre Kristos Desta", "Erhabor Emokpae", 
             "Dumile Feni", "Sydney Kumalo", "Iba N'Diaye", "Tshibumba", 
             "Chris Doyle", "Justo Gallego", "S. Mark Gubb", "Bedwyr Williams", 
             "Gil Blank", "Jeffery Davis", "Jules de Balincourt", "Toby Barnes",
             "Jean de Piepape", "Mac Premo", "Pip Chodorov", "Veli Granö", "Ilkka Halso",
             "Pekka Jylhä", "Reijo Kela", "Erkki Kurenniemi", "Sami Sänpäkkilä",
             "Jari Silomäki", "Edgar Martins", "Ry Rocklen", "Dread Scott", 
             "Alex Da Corte", "Zak Kitnick", "Lee Isaac Chung", "Deville Cohen",
             "Brody Condon", "Caleb Considine", "Debo Eilers", "Redmond Entwistle",
             "Franklin Evans", "Bruno Jakob", "Tan Lin", "Mathieu Mategot", 
             "Saul Melman", "Rashaad Newsome", "Conrad Ventur", "Harold Mendez",
             "Edgardo Aragón", "Ilja Karilampi", "Dale Brockman Davis", "Alonzo Davis",
             "Ulysses Jenkins", "Tyrus Wong", "Korakrit Arunanondchai", 
             "Korapat Arunanondchai", "Jef Cornelius", "Colin Christian", "Charlie Ahearn",
             "Lazbent Pavel Escobedo Amaral", "Brennan Buck", "Wes McGee", 
             "DK Osseo-Assare", "Mecky Reuss", "Himat M. Ali", "Dia al-Azzawi",
             "Rafa Nasiri", "E'wao Kagoshima", "Aki Onda", "Kern Samuel", "Andro Eradze",
             "Jean Katambayi Mukendi", "Dylan Peirce", "Zhou Tao", "He Xiangyu", 
             "Saul Ostrow", "Louis Grenier", "Alec Bernstein", "Charlie Morrow", 
             "Kariya Hiroshi", "Marcel Dot", "Radford Thomas", "Wolfgang Luy", 
             "Wayne Hazen", "Avital Oz", "Wolfgang Mally", "Robin Lee Crutchfield",
             "Al Calderaro", "Dale Frank", "Harald Klingelhöller", "Gerry Morehead",
             "Kent Shell", "Christof Kohlhöfer", "Willi Smith", "Kees de Goede", 
             "Francois Martin", "Klause Schmitt", "Gustavo Ojeda", "Allan Wexler",
             "Spencer Holst", "Alejandro Arango", "Ingo Günther", "Rene Daniels", 
             "Louis Renzoni", "Sur Rodney (Sur)", "Honoré Daumier", "Louis Laurita",
             "Yee Jan Bao", "Johnie Hugh Horn", "Rolando Briseño", "Jean-Luc Poivret",
             "Robin Utterback", "Bruno Ehrs", "Chris Strachwitz", "A. Leroy", 
             "Emmanuel Pereire", "Bruno Dufourmantelle", "Patrice Giorda", "Wes Jones",
             "Chris Scholz", "Bolek Greczynski", "Mel Rosenthal", "Alejandro Sina",
             "Colin Chase", "Cameron McNall", "Jean-Luc Vilmouth", "Sérgio Bernardes",
             "Adir Sodre", "Mel Ziegler", "Rene Pierre Allain", "Harold Baumbach",
             "Spencer Gregory", "Ik-Joong Kang", "Ange Leccia", "Glen Seator", 
             "Olivier Ferrieux", "Reiner Goerss", "Xinping Wang", "Alexis Rockman", 
             "Du Wang", "Juan Galdeano", "Celeste Boursier-Mougenot", "Beat Huber",
             "Gibb Slife", "Aidas Bareikis", "Lionel Esteve", "Tommi Grönlund", 
             "Petteri Nisunen", "Marko Peljhan", "Vincente Razo", "Chris Sauter",
             "Colin Beatty", "Hubert Duprat", "Jussi Heikkila", "Vincenzo Agnetti",
             "Nicola De Maria", "Tano Festa", "Francesco Lo Savio", "Amedeo Martegani",
             "Remo Salvadori", "Ettore Spalletti", "Franco Vaccari", "Eike Becker",
             "Safy Etiel", "Jürgen Frisch", "Bertrand Lavier", "Luigi Ontani", 
             "Muhal Abrams", "Chris Cutler", "Tod Dockstader", "Arto Lindsay", 
             "Lou Reed", "Ryuichi Sakamoto", "Loudon Wainwright", "Fassih Keiso",
             "Tehching Hsieh", "Yang Lian", "Hiroshige Fukuhara", "Taka Furuhashi",
             "Kouki Hasei", "Gabin Ito", "Keiji Ito", "Sousei Kazuki", "Ryota Kuwakubo",
             "Taiyo Matsumoto", "Kouji Morimoto", "Tokiharu Noto", "Katsuhiro Otomo",
             "Motoshi Sato", "Nakagawa Sochi", "Takayuki Takeya", "Hideyuki Tanaka",
             "Katsuya Terada", "Tex Avery", "Garri Bardin", "Emile Cohl", "Joshua Davis",
             "Xeth Feinberg", "Alex Galloway", "Munro Galloway", "Jerzy Kuciz",
             "Sebastian Luetergt", "Winsor McCay", "Panajotis Mihalatos", 
             "Chris Bors", "Akshay Desai", "Manabu Inada", "Carlo Zanni", 
             "Gim Hongsok", "Isozaki Michiyoshi", "Bruno Peinado", "Dario Solman", 
             "Gustavo Artigas", "Miguel Calderon", "Wayne Guyton", "Karlis Rekevics", 
             "Augusto Arbizo", "Antoine Berghs", "Declan Clarke", "Jongku Kim", 
             "Jean-Francois Moriceau", "Katsuhiro Saiki", "Erik Hanson", "Wayne Gonzales", 
             "Alex Kwartler", "Chris Martin", "Tomislav Buntak", "Alen Floričić", 
             "Kristian Kožul", "Wensheng Dong", "Hu Jieming", "Yongfeng Ma", "Tan Xu",
             "Ohad Meromi", "Ricky Sears", "Louis Cameron", "Nico Krebs", "Taiyo Onorato",
             "Andisheh Avini", "Kent Henricksen", "Geof Oppenheimer", "Devendra Banhart",
             "Corey D'Augustine", "Luke Fowler", "Saul Levine", "Maury Colton III",
             "Gandalf Gavan", "Ari Marcopoulos", "Francesco Vezzoli", "Eyal Danieli",
             "Radcliffe Bailey", "Dario Robleto", "Zak Kitnick", "Chris Wiley", 
             "Khalid Al Gharaballi", "Nanu Al-Hamad", "Abdullah Al-Mutairi", 
             "Barrak Alzaid", "Zhao Zhao", "Harald Thys", "Reginald Dwayne Betts",
             "American Artist", "Conor Broderick", "Halim Flowers", "Ojore Lutalo",
             "Welmon Sharlhorne", "Joshua Chuquimia Crampton", "Devin N. Morris", 
             "G.H. Hovagimyan", "Sandro Martini", "Jan Yoors", "Frederick Spratt", "Erik Steinbrecher")

point22 <- c("Jan Hafström", "Jan van den Dobbelsteen", "Jan Baracz", "Jan Kopp",
             "Alex Locadia", "A. Neumann", "A. (Tony) Nali", "Noel Harding", "A. Kynn Forgach",
             "A. Leroy", "B. Wurtz", "J.J. Murphy", "L. Brandon Krall", "H. D.")

point52 <- c("Mabou Mines", "Ralston Farina", "Centre for Experimental Art and Communication",
             "Yuki Hartman", "S.E.M. Ensemble", "Disband", "Archizoom Associati",
             "Grupo UFO", "Ehry", "Morgan Thomas", "AMMO", "Church of the Subgenius",
             "Krononauts", "Strange Party", "Die Tödliche Doris", "Teufelbergproduktion",
             "Survival Research Laboratories", "Fast Forward", "Queens Symphony Orchestra",
             "Fortuyn/O'Brien", "Ant Farm", "Haus-Rucker-Co", "Venturi, Rauch and Scott Brown",
             "Red Square Design", "Stiletto", "Lascari", "Medical Hermeneutics",
             "The Peppers", "IRWIN", "Blacklips Performance Cult", "P.O.N.Y.", 
             "Diabologum", "Encore", "Maison Martin Margiela", "Gran Fury", "AMA",
             "Kunstlabor", "Mutamussik", "Fluxus", "New Analysis Group", 
             "Southern Artists Salon", "2dk: David d'Heilly & Kayoko Ota", 
             "Edge: Michael Chan & Gary Chang", "Buero Friedrich",
             "Harvard Project on the City: Shopping", "Herzog & de Meuron, Basel", 
             "Low-Flame", "The Butoh Rockettes", "Granular Synthesis", "Avirex", 
             "Burberry", "Comme des Garçons", "Corpo 9", "C.P. Company", "Dolce & Gabbana",
             "Foster", "Gucci", "Maharishi", "Moschino", "Prada", "Rayban-Luxottica",
             "Sportswear Company", "Stone island", "Thinkdance", "Chelin", "TANY", 
             "El Perro", "PSJM", "n ARCHITECTS", "eteam", "Juneau Projects", 
             "caraballo-farman", "Big Room", "Type A", "Berwick Street Film Collective",
             "Lesbian Art Project", "Pink Twins", "Screaming Men", "Archigram", 
             "My Barbarian", "Primary Information", "Superstudio", "An Atlas of Radical Cartography",
             "The Bruce High Quality Foundation", "Delusional Downtown Divas", 
             "DETEXT", "Grand Openings", "CONFETTISYSTEM", "Office for Political Innovation",
             "ECKHAUS LATTA", "fierce pussy", "Escobedo Soliz Studio", "Bair Balliet",
             "Dream the Combine", "FreelandBuck", "OFICINAA", "Low Design Office (LOWDO)",
             "Matter Design", "TO", "Deep Dish TV", "BlackMass Publishing",
             "Las Nietas de Nonó", "Shanzhai Lyric", "Poncili Creación", 
             "POOL (Performance On One Leg)", "Coach House Press", "La Groupe des Beaux Arts",
             "Nelvana Limited", "N.E Thing Co. Ltd.", "Vancouver School of Art: Graphic Design Students",
             "Friday Architects", "Stamp Show", "Morgan Fisher", "Morgan Bassichis", 
             "Kai Eric", "Zev Schrott", "Lee Sokol", "Robin Lehrer", "Robin Klingensmith",
             "Robin Holder", "DJ McDonald", "J.J. Murphy", "A. Kimberlin Blackburn", "Hiwa K",
             "Jean Paul Gautier", "Valentino", "Giorgio Armani", "Video Zagreb", 
             "Costa", "M. Demuro", "DNA", "Futura 2000", "Firelight", "Irva", 
             "Squat Theater", "TODT", "C.J Collins", "Future Tents", "NASA", "Videofreex",
             "WGBH-TV: Independent Video", "R.T. Livingston", "Casa Nicaragua", 
             "Cispes", "Siggraph '83", "Exchange T.V.", "Paper Tiger Television",
             "Radio Venceremos", "Raindance Foundation", "A Touch of Class", 
             "Double Dutch Dancers", "Lizard", "Hawaii Art and Energy, Inc.", 
             "Pacific Street Film Collective", "Channel Four Television", 
             "Crew of Battlefields Project", "K.O.S. (Kids of Survival)", 
             "Empire State Photographers", "Information Fiction Publicite (IFP)", 
             "Samba School of San Miguel", "A.T.W.", "Screammachine", "The Rivington School",
             "Y-Space", "Actress", "FAT magazine", "Sincerely Yours Escorts", 
             "Standard and Poor", "The Stand", "Up & Co", "WFMU", "zingmagazine", 
             "E.F. Costa", "Kyupi Kyupi", "3 de luxe", "Bless", "Grüntuch-Ernst Architects",
             "Honey-Suckle Company", "LSD", "raumlaborberlin", "Sauerbruch Hutton",
             "Stylegames.net", "WMF", "Big Room", "Group Material", "Chop Shop", 
             "Chris & Cosey", "Cibo Matto", "¡Cubanismo!", "Yamataka Eye", "Fischerspooner",
             "Impossible Music", "I-Sound", "The Residents", "Sonic Youth", "Steinski",
             "The Art Guys", "Ages 5 & Up", "Exonemo", "Groovisions", "Nihon-Ishina", 
             "Stereotype Produkts", "TGV", "Tugboat", "Tycoon Graphics", "Basicray", 
             "JODI", "8gg", "Raw Sewage", "Minus Space", "Base", "Guerrilla Art Action Group",
             "Harvard University Graduate School of Design", "Chim↑Pom", "BFFA3AE", 
             "GCC", "ACT UP, New York", "Pussy Riot", "The Radek Community", "Voina",
             "MSHR", "GisMo (Jessica Gispert and Crystal Pearl Molinary)", 
             "Standing On The Corner")

point82 <- c("Angels Ribe", "Evriah Bader", "Ralston Farina", "Hass Murphy", 
             "Chi Chi Valenti", "Miss Ming Vauze", "Didi Dubelyew", "Helina Hughes",
             "Rii Kanzaki", "Tomiyo Sasaki", "Tonie Roos", "Leslie-Jane Pessemier",
             "Nat Dean", "Ame Gilbert", "Catti (Catherine James)", "Leni Andrade",
             "Shujane Lee", "Bisa Washington", "Leslie Sharpe", "Hannan Ashrawi",
             "Mistress Sonja Blaze", "Joffi D'Incher", "Suse Eichinger", "Suchan Kinoshita",
             "Itty Neuhaus", "Alix Lambert", "Valérie Pigato", "Tone E. Ch. Johansen",
             "Joke Robaard", "Aki Fujiyoshi", "Kerry Mullett", "Cerle Ramo Nash",
             "J. Morgan Puett", "Zvezdana Rogic", "Ute Weiss-Leder", "Wu Mali",
             "Jinai Kim", "Bul Lee", "Sohn-Joo Minn", "Anna Gabriel", "Liadin Cooke",
             "Mo White", "Beck Underwood", "Claude Wampler", "Wen-Shuan Yang",
             "Anna Conway", "Anna Craycoft", "Rä di Martino", "Alexis Hunter",
             "Lole de Freitas", "Anna Keier", "Wynne Greenwood", "Aki Sasamoto",
             "Rey Akdogan", "Genesis P-Orridge", "Sister Karen Boccalero", "Math Bass",
             "Robin Graubard", "Dora Budor", "Tolia Astakhishvili", "Geumhyung Jeong",
             "Ser Serpas", "Pat Ivers", "Pat Tavenner", "Candida Alvarez", "Leslie Lalehzar",
             "Jamillah Jennings", "Francesca Jones", "A. Kimberlin Blackburn", "Ame Gilbert",
             "Robin Bruch", "Gioia Timpanelli", "Inge Mahn", "Alba Cane", "Dee Axelrod",
             "Lilly Brody", "Isolde Wawrin", "Paulette Nenner", "Pat Place", "Robin Tewes",
             "Anna Bisso", "Jeanie Black", "Marlene Bloomer", "Leslie Eve Child",
             "Kris Waneck", "Maz Brook", "Kieko Bonk", "Toyko Hirata", "Jessie Benton-Evans-Gray",
             "Pene Bonita", "Josely Carvalho", "Sydney Blum", "Madison Bell", 
             "Tuija Lindstrom", "Merian Soto", "Katrini Krinsky", "Faithanne Carapella",
             "Sabra Moore", "Vernita Nemec", "Hedy O'Beil", "Rhea Sanders", 
             "Katheryn Anne Sins", "Selina Trieff", "Suruchi Chand", "Jean Gallagher",
             "Renee Rockoff", "Muna Tseng", "Adrienne Farb", "Jerri Allyn", 
             "Lori Beth Blaikie", "Penny Coleman", "Nanue Lelue", "Robyn Almaleh",
             "Margot Lovejoy", "Serena Bocchino", "Merrin Eirth", "Geraldine Erman",
             "Anna Mariani", "Roxanne Blanchard", "Mirjam de Zeeuw", "Polly Kiesel",
             "Lynn Robinson", "Camilla Warenskjold-Dybvik", "Antonella Piemontese",
             "Daina Shobrys", "Esperanza Cortes", "Kay Miller", "Solfrid Mortensen",
             "Robin Stanaway", "Lynn Wilder", "Anna Plotnicka", "Andromahi Kefalos",
             "Hillary Leone", "Katharina Karrenberg", "Dara Silverman", "Tatyana Gubash",
             "Buffie Johnson", "Margrit Lewczuk", "L.C. Armstrong", "Yvette Helin",
             "Zaporah Jacobs", "Lanie Lee", "Rise Cale", "Juliane Duda", "Gunda Foerster",
             "Ursula Kraft", "Edy Ferguson", "Liza May Post", "Juana Valdes",
             "Clara Williams", "Mandy Ming-Yin Yim", "Fabiana de Barros", "Juliet Lea",
             "Rekha Rodwittiya", "Alma Suljevic", "Adriana Varejão", "Ciara Finnegan", 
             "Jean van Heeswijk", "Danica Phelps", "Jovi Schnell", "Nikki Lee", 
             "Tomoko Takahashi", "Fatimah Tuggar", "Jan Harrison", "Kaisu Koivisto", 
             "Tamara Grcic", "Dadamaino", "Raffaella Nappo", "Sabrina Mezzagui",
             "Adriana Arenas", "Tracey Baran", "Chakaia Booker", "Lucky DeBellevue",
             "Jyung Mee Park", "Kaffe Matthews", "Genken Montgomery", "Adrianna Sa",
             "Carola Dertnig", "Ivana Franke", "Midori Araki", "Hanako Kunishi",
             "Hitomi Uchikura", "Yuka Wake", "Alexandra Korejwo", "Liane Lang", 
             "Lucretia Knapp", "Eline McGeorge", "Jeanine Oleson", "Jessie Shefrin",
             "Ottonella Mocellin", "Valerie Prot", "Amanda Ralph", "Constanze Schweiger",
             "Katleen Vermeir", "Shoshana Dentz", "Cadence Giersbach", "Leemour Pelli",
             "Yun-Fe Jin-Hua", "Julianne Swartz", "Darinka", "Petra Lindholm", "Dianna Frid",
             "Kira Lynn Harris", "Xiuwen Cui", "Songhua Li", "Sungmi Lee", "Lisi Raskin",
             "Felisa Funes", "Meredyth Sparks", "McKendree Key", "Senam Okudzeto",
             "Margie Strosser", "Tamara Gonzales", "Prema Murthy", "Amalia Mesa-Bains",
             "Shizuka Yokomizo", "Carey Young", "Vinca Kruk", "Sophia Al Maria",
             "Fatima Al Qadiri", "Amal Khalaf", "Samara Golden", "Amal Kenawy", 
             "Jordon Kasey", "Jillian Mayer", "Carole Alden", "Tameca Cole", "Amber Rose Daniel",
             "Nereida García-Ferraz", "Chandra McCormick", "Cedar Mortenson", 
             "Rowan Renee", "Treacy Ziegler", "Elysia Chuquimia Crampton", 
             "Charisse Pearlina Weston", "Glenda Hydler", "Yeohlee Teng", "Kei Takei")

onepoint02 <- c("Myrel Chernick", "Gillian Bradshaw-Smith", "Elizebeth Egbert", 
                "Vita Giorgi", "Madelon Jones", "Dee Shapiro", "Arlene Slavin", 
                "Ilise Greenstein", "Laurace James", "Clover Vail", "Merrill Wagner",
                "Frankie Mann", "Rae Berolzheimer", "Blondell Cummings", "Toby MacLennan",
                "Pooh Kaye", "Cookie Mueller", "Birgitta Liljebladh", "Lyne Lapointe",
                "Danita Geltner", "Lynn Swanson", "Marion Gray", "Rae Langston", 
                "Su Friedrich", "Chick Strand", "Lynn Klosky", "Jan Oxenberg", 
                "C. Ann Carter", "Gal Costa", "Su-Chen Hung", "Pene Bonita", 
                "Lynn McCary", "Luce Irigaray", "Marijke van Warmerdam", "Jody Sperling",
                "Charley Friedman", "Pat Oleszko", "May Wilson", "Jerry the Marble Faun",
                "Guerrilla Girls", "Toni Morrison", "Ora Lerman", "Janice Becker", 
                "Toby Buonagurio", "Mierle Laderman Ukeles", "Eugéne Leroy")


Full_PS1 <- Full_PS1 |>
  mutate(GenderConf2 = case_when(
    Gender == "female" ~ 1,
    Gender == "male" ~ 0, 
    Full_PS1$artistName %in%  point02 ~ 0,
    Full_PS1$artistName %in%  point22 ~ 0.2,
    Full_PS1$artistName %in%  point52 ~ 0.5,
    Full_PS1$artistName %in%  point82 ~ 0.8,
    Full_PS1$artistName %in%  onepoint02 ~ 1, 
    TRUE ~ 0.5
  ))

# bot 3

point03 <- c("Lee Breuer", "Jean Dupuy", "Willoughby Sharp", "Ralston Farina", 
             "Angels Ribe", "Evriah Bader", "Milet Andrejevic", "Jan HafstrÃ¶m", 
             "Skip La Plante", "Amado Aldaraca", "Licio Isolani", "Gilles Larrain", 
             "Jerry Clapsaddle", "Kendall Shaw", "Zadik Zadikian", "Manny Farber", 
             "Caspar Henselmann", "Kent Floeter", "Lou Forgione", "Lowell Cross", 
             "Alex Kayser", "Jerry McMillan", "Gene Tyranny", "Morgan Fisher", 
             "Noel Harding", "Jaime Ardila", "Al Robbins", "A. David Christian", 
             "Jean Mauboules", "Koki Doktori", "Addison Parks", "Gerrit Henry", 
             "Rene Ricard", "Krijn Giezen", "Gerd Rohling", "Cosimo Di Leo Ricatto",
             "Ehry", "Morgan Thomas", "Kes Zapkus", "Kai Eric", "Kazimir Passion",
             "Zev Schrott", "Ter Hell", "Reinhard Niedermeier", "Henk Visch", 
             "Louis Chacallis", "Bo Trankell", "Petter Zennstrom", "Erland Cullberg",
             "Enno Hallek", "Georgii Kizevalter", "Fedo Ertl", "Jan Hoet", 
             "Jean-Marc Lévy-Leblond", "Joad Raymond", "Rocco Di Pietro", 
             "Lee Roy Champagne", "Nat Dean", "Al Honig", "Bryan Rogers", "Q.J. Stephenson",
             "Tatsumi Orimoto", "Chieo Senzaki", "Mo Bahc", "Ho Yoo Choi", 
             "Jean Patrick Icart-Pierre", "Lascari", "Bing Lee", "Taeho Lee", "Ming Mu-Ray",
             "Franc Palaia", "Dale Wilhelm", "Vitas Stasunas", "Min Tanaka", 
             "Milovan Markovic", "Even Bie-Larsen", "Kavin Buck", "Chisen Furukawa",
             "Franklin Schaffner", "Alex Locadia", "R.S. Wolkenstein", "Marcel Dot",
             "M.L. Heivly", "E.F. Higgins", "Radford Thomas", "Wayne Hazen", "Jeffery Davis",
             "Jules de Balincourt", "Al Masson", "Mac Premo", "Pip Chodorov", "Veli GranÃ",
             "Ilkka Halso", "Pekka Jylhä", "Reijo Kela", "Erkki Kurenniemi", "Pink Twins",
             "Sami Sänpäkkilä", "Screaming Men", "Jari Silomäki", "Edgar Martins",
             "Ry Rocklen", "Dread Scott", "Alex Da Corte", "Zak Kitnick", "Lee Isaac Chung",
             "Brody Condon", "Caleb Considine", "Debo Eilers", "Redmond Entwistle", "Franklin Evans",
             "Bruno Jakob", "Tan Lin", "Mathieu Mategot", "Saul Melman", "Rashaad Newsome",
             "Conrad Ventur", "Harold Mendez", "Rey Akdogan", "Edgardo AragÃ³n", 
             "Ilja Karilampi", "Genesis P-Orridge", "Dale Brockman Davis", "Alonzo Davis",
             "Ulysses Jenkins", "Tyrus Wong", "Korakrit Arunanondchai", "Korapat Arunanondchai", 
             "Jef Cornelius", "Colin Christian", "Math Bass", "Charlie Ahearn", 
             "Morgan Bassichis", "Chris Hoover", "Chris Brown", "Scot Gresham-Lancaster",
             "Richie Hawtin", "Chris Doyle", "Justo Gallego", "LA (Laton Alton) Huffman",
             "S. Mark Gubb", "Bedwyr Williams", "Gil Blank","Noel Harding", "Wolfgang Mally",
             "Al Calderaro", "Dale Frank", "Harald Klingelhöller", "Gerd Rohling",
             "Jean Dupuy", "Louis Grenier", "Louis Chacallis", "Kees de Goede", 
             "Ter Hell", "Francois Martin", "Klause Schmitt", "Gustavo Ojeda", "Saul Ostrow", 
             "Standish Lawder", "Allan Wexler", "Spencer Holst", "Alejandro Arango",
             "Ingo Günther", "Jan van den Dobbelsteen", "Rene Daniels", "Louis Renzoni",
             "Sur Rodney (Sur)", "Honoré Daumier", "Louis Laurita", "Yee Jan Bao",
             "Toyko Hirata", "Johnie Hugh Horn", "Jean-Luc Poivret", "Bruno Ehrs", 
             "Chris Strachwitz", "Bruno Dufourmantelle", "Patrice Giorda", "Wes Jones",
             "Chris Scholz", "Fortuyn/O'Brien", "Bolek Greczynski", "Emmanuel Pereire",
             "Mel Rosenthal", "Alejandro Sina", "Harald Klingelhöller", "Colin Chase",
             "Cameron McNall", "Christiaan Bastiaans", "Jean-Luc Vilmouth", "Sérgio Bernardes",
             "Adir Sodre", "Fortuyn/O'Brien", "Mel Ziegler", "Rene Pierre Allain", "Harold Baumbach",
             "Spencer Gregory", "Ik-Joong Kang", "Ange Leccia", "Glen Seator", 
             "Olivier Ferrieux", "Reiner Goerss", "Alexis Rockman", "Juan Galdeano", 
             "Vincente Razo", "Chris Sauter", "Colin Beatty", "Hubert Duprat", 
             "Jussi Heikkila", "Vincenzo Agnetti", "Nicola De Maria", "Tano Festa",
             "Francesco Lo Savio", "Amedeo Martegani", "Remo Salvadori", "Ettore Spalletti",
             "Franco Vaccari", "Eike Becker", "Beat Huber", "E.F. Costa", "Arrow Mueller", 
             "Lucky DeBellevue", "Ethan Crenson", "Bertrand Lavier", "Luigi Ontani",
             "Muhal Abrams", "Chris Cutler", "Tod Dockstader", "Yamataka Eye", "Actress", 
             "Keenan Lawler", "Arto Lindsay", "Genken Montgomery", "Genesis P-Orridge", 
             "Lou Reed", "Ryuichi Sakamoto", "Steinski", "Loudon Wainwright", "Fassih Keiso",
             "Tehching Hsieh", "Yang Lian", "Alexis Rockman", "Hiroshige Fukuhara",
             "Taka Furuhashi", "Kouki Hasei", "Gabin Ito", "Keiji Ito", "Sousei Kazuki",
             "Ryota Kuwakubo", "Taiyo Matsumoto", "Kouji Morimoto", "Tokiharu Noto", 
             "Smelly (Dai Okazaki)", "Katsuhiro Otomo", "Motoshi Sato", "Nakagawa Sochi",
             "Takayuki Takeya", "Hideyuki Tanaka", "Katsuya Terada", "Tex Avery", 
             "Garri Bardin", "Emile Cohl", "Joshua Davis", "Xeth Feinberg", "Alex Galloway",
             "Munro Galloway", "Jerzy Kuciz", "Sebastian Luetergt", "Winsor McCay",
             "Panajotis Mihalatos", "Chris Bors", "Akshay Desai", "Manabu Inada", 
             "Carlo Zanni", "Gim Hongsok", "Isozaki Michiyoshi", "Bruno Peinado", 
             "Dario Solman", "Gustavo Artigas", "Miguel Calderon", "Wayne Guyton", 
             "Karlis Rekevics", "Augusto Arbizo", "Antoine Berghs", "Declan Clarke", 
             "Yun-Fe Jin-Hua", "Jongku Kim", "Jean-Francois Moriceau", "Katsuhiro Saiki", 
             "Jérôme Basserode", "Bartolomeu dos Santos", "Jules de Balincourt",
             "Erik Hanson", "B. Wurtz", "Wayne Gonzales", "Cannon Hudson", "Alex Kwartler",
             "Chris Martin", "Tomislav Buntak", "Alen Floričić", "Kristian Kožul",
             "8gg", "Wensheng Dong", "Hu Jieming", "Songhua Li", "Yongfeng Ma", "Tan Xu",
             "Ohad Meromi", "Ricky Sears", "Louis Cameron", "Nico Krebs", "Taiyo Onorato", 
             "Andisheh Avini", "Corey D'Augustine", "Luke Fowler", "Saul Levine", 
             "Maury Colton III", "Gandalf Gavan", "Chris Martin", "Gandalf Gavan",
             "Ari Marcopoulos", "Dario Robleto", "Francesco Vezzoli", "Eyal Danieli", 
             "Radcliffe Bailey", "Standish Lawder", "Tehching Hsieh", "Zak Kitnick", 
             "Chris Wiley", "Khalid Al Gharaballi", "Nanu Al-Hamad", "Abdullah Al-Mutairi",
             "Barrak Alzaid", "Zhao Zhao", "Harald Thys", "Jordon Kasey", "Reginald Dwayne Betts",
             "Conor Broderick", "Halim Flowers", "Ojore Lutalo", "Welmon Sharlhorne", 
             "Joshua Chuquimia Crampton", "Devin N. Morris", "Zadik Zadikian",
             "G.H. Hovagimyan", "Saul Ostrow", "Emmanuel Pereire", "Jean Dupuy", 
             "Sandro Martini", "Jan Yoors", "Frederick Spratt", "Cameron McNall",
             "IRWIN", "Henk Visch", "Erik Steinbrecher", "Luigi Ontani", 
             "Zilvinas Kempinas", "Jeppe Hein", "Manny Farber", "Xefirotarch", 
             "OBRA Architects", "Melvin Charney", "Dimitry Merinoff", "Adrian Scott", 
             "Morgan Fisher", "Louis Grenier", "Willi Smith", "Gerry Morehead", 
             "Noriyuki Haraguchi", "Franky Kong", "Claude Lévêque", "Mick O'Shea", 
             "Ashkan Sahihi", "Wolfgang Plöger", "Hedi Slimane", "Johnston Foster",
             "Ari Marcopoulos", "Loris Cecchini", "Abbas Kiarostami", "Kris Martin", 
             "Børre Sæthre", "Leandro Ehrlich", "Alejandro Jodorowsky", "Surasi Kusolwong",
             "HWKN Hollwich Kushner", "Motandi Ouoba", "IM Heung-soon", "Tomáš Rafa",
             "Umar Rashid", "Chris Yuin", "Maury Colton III", "Gandalf Gavan", 
             "Eyal Danieli", "Radcliffe Bailey", "Standish Lawder")



point23 <- c("Willoughby Sharp", "Ralston Farina", "Angels Ribe", "Evriah Bader",
             "Skip La Plante", "Amado Aldaraca", "Licio Isolani", "Gilles Larrain",
             "Jerry Clapsaddle", "Kendall Shaw", "Zadik Zadikian", "Manny Farber",
             "Caspar Henselmann", "Kent Floeter", "Lou Forgione", "Lowell Cross",
             "Alex Kayser", "Jerry McMillan", "Gene Tyranny", "Morgan Fisher", 
             "Noel Harding", "Jaime Ardila", "Al Robbins", "A. David Christian",
             "Jean Mauboules", "Koki Doktori", "Addison Parks", "Gerrit Henry", 
             "Rene Ricard", "Krijn Giezen", "Gerd Rohling", "Cosimo Di Leo Ricatto",
             "Ehry", "Morgan Thomas", "Kes Zapkus", "Kai Eric", "Kazimir Passion", 
             "Zev Schrott", "Ter Hell", "Reinhard Niedermeier", "Henk Visch", 
             "Louis Chacallis", "Bo Trankell", "Petter Zennstrom", "Erland Cullberg",
             "Enno Hallek", "Georgii Kizevalter", "Fedo Ertl", "Jan Hoet",
             "Joad Raymond", "Rocco Di Pietro", 
             "Lee Roy Champagne", "Nat Dean", "Al Honig", "Bryan Rogers", "Q.J. Stephenson", 
             "Tatsumi Orimoto", "Chieo Senzaki", "Mo Bahc", "Ho Yoo Choi", 
             "Jean Patrick Icart-Pierre", "Lascari", "Bing Lee", "Taeho Lee", "Ming Mu-Ray",
             "Franc Palaia", "Dale Wilhelm", "Vitas Stasunas", "Min Tanaka", 
             "Milovan Markovic", "Even Bie-Larsen", "Kavin Buck", "Chisen Furukawa",
             "Franklin Schaffner", "Alex Locadia", "R.S. Wolkenstein", "Marcel Dot",
             "M.L. Heivly", "E.F. Higgins", "Radford Thomas", "Wayne Hazen", 
             "Jeffery Davis", "Jules de Balincourt", "Al Masson", "Mac Premo", "Pip Chodorov",
             "Ilkka Halso", "Reijo Kela", "Erkki Kurenniemi",
             "Pink Twins", "Screaming Men",
             "Edgar Martins", "Ry Rocklen", "Dread Scott", "Alex Da Corte", "Zak Kitnick",
             "Lee Isaac Chung", "Brody Condon", "Caleb Considine", "Debo Eilers",
             "Redmond Entwistle", "Franklin Evans", "Bruno Jakob", "Tan Lin", "Mathieu Mategot",
             "Saul Melman", "Rashaad Newsome", "Conrad Ventur", "Harold Mendez", 
             "Rey Akdogan", "Edgardo AragÃ³n", "Ilja Karilampi", "Genesis P-Orridge",
             "Dale Brockman Davis", "Alonzo Davis", "Ulysses Jenkins", "Tyrus Wong",
             "Korakrit Arunanondchai", "Korapat Arunanondchai", "Jef Cornelius",
             "Colin Christian", "Math Bass", "Charlie Ahearn", "Morgan Bassichis",
             "Chris Hoover", "Chris Brown", "Scot Gresham-Lancaster", "Richie Hawtin",
             "Chris Doyle", "Justo Gallego", "LA (Laton Alton) Huffman", "S. Mark Gubb",
             "Bedwyr Williams", "Gil Blank", "Costa", "M. Demuro", "Alba Cane", 
             "Kent Shell", "R.T. Livingston", "Rii Kanzaki", "Frankie Mann", "Rolando Briseño",
             "Madison Bell", "H. D.", "A. Leroy", "B. Wurtz", "Adir Sodre", "Lionel Esteve",
             "Tommi Grönlund", "Petteri Nisunen", "Marko Peljhan", "Aidas Bareikis",
             "Fassih Keiso", "Tokiharu Noto", "Smelly (Dai Okazaki)", "Panajotis Mihalatos",
             "Zhao Zhao", "Harald Thys", "Claude Lévêque")



point53 <- c("Mabou Mines", "Centre for Experimental Art and Communication", "S.E.M. Ensemble",
             "Disband", "Church of the Subgenius", "Krononauts", "Strange Party", 
             "Miss Ming Vauze", "Pooh Kaye", "Didi Dubelyew", "Queens Symphony Orchestra",
             "DJ McDonald", "Die Tödliche Doris", "Teufelbergproduktion", 
             "Survival Research Laboratories", "AMMO", "Tracey Berg", "Chi Chi Valenti", 
             "Video Zagreb", "DNA", "Futura 2000", "Firelight", "Irva", "Squat Theater",
             "TODT", "Fluxus", "Future Tents", "NASA", "Videofreex", "WGBH-TV: Independent Video",
             "Casa Nicaragua", "Cispes", "Exchange T.V.", "Paper Tiger Television",
             "Radio Venceremos", "Raindance Foundation", "A Touch of Class", 
             "Double Dutch Dancers", "Pacific Street Film Collective", "Channel Four Television",
             "Crew of Battlefields Project", "Hawaii Art and Energy, Inc.", "Lizard", 
             "K.O.S. (Kids of Survival)", "Empire State Photographers", "Information Fiction Publicite (IFP)",
             "Samba School of San Miguel", "The Rivington School", "FAT magazine",
             "Sincerely Yours Escorts", "Standard and Poor", "The Stand", "Up & Co",
             "WFMU", "zingmagazine", "Screammachine", "Y-Space", "3 de luxe", "Bless", 
             "Grüntuch-Ernst Architects", "Honey-Suckle Company", "LSD", "raumlaborberlin", 
             "Sauerbruch Hutton", "Stylegames.net", "WMF", "Big Room", "Group Material",
             "Chop Shop", "Chris & Cosey", "Cibo Matto", "¡Cubanismo!", "Fischerspooner",
             "Impossible Music", "I-Sound", "The Residents", "Sonic Youth", "The Art Guys",
             "Ages 5 & Up", "Exonemo", "Groovisions", "Kyupi Kyupi", 
             "Nihon-Ishina", "Stereotype Produkts", "TGV", "Tugboat", "Tycoon Graphics",
             "Basicray", "JODI", "Darinka", "8gg", "Minus Space", "Base", 
             "The Bruce High Quality Foundation", "Fluxus", "Guerrilla Art Action Group", 
             "Harvard University Graduate School of Design", "Raw Sewage", "Chim↑Pom", 
             "BFFA3AE", "GCC", "ACT UP, New York", "Chim↑Pom", "Pussy Riot", 
             "The Radek Community", "Voina", "MSHR", "GisMo (Jessica Gispert and Crystal Pearl Molinary)",
             "Standing On The Corner", "Mabou Mines", "Guerrilla Girls", 
             "Queens Symphony Orchestra", "Gelatin", "Dearraindrop", "Xefirotarch",
             "OBRA Architects", "Ball-Nogues Studio", "WORK Architecture Company",
             "MOS Architects", "Performa 09", "CODA", "The Living", "Karrabing Film Collective",
             "For Freedoms", "Warchurch (Skech185 and Analog[ue] Tape Dispenser)",
             "Minus Space", "Base", "The Bruce High Quality Foundation", "Guerrilla Art Action Group",
             "Harvard University Graduate School of Design", "ROY")



point83 <- c("Robin Lehrer", "Ilise Greenstein",
             "Laurace James", "Clover Vail", "Hass Murphy", "Frankie Mann", "A. Kimberlin Blackburn",
             "Helina Hughes", "Rii Kanzaki", "Tomiyo Sasaki", "Birgitta Liljebladh", 
             "Tonie Roos", "Luce Irigaray", "Ame Gilbert", "Robin Holder",
             "Lynn Klosky", "Leslie-Jane Pessemier", "Lynn Swanson", "Marion Gray",
             "Rae Langston", "Su-Chen Hung", "Pene Bonita", "Bisa Washington", 
             "Leslie Sharpe", "Lynn McCary", "Aki Fujiyoshi", "Anna Gabriel", 
             "Liadin Cooke", "Mo White", "Beck Underwood", "Claude Wampler", 
             "Anna Conway", "Anna Craycoft", "Alexis Hunter", "Lole de Freitas",
             "Anna Keier", "Marijke van Warmerdam", "Dora Budor", "Tolia Astakhishvili",
             "Geumhyung Jeong", "Ser Serpas", "Pat Oleszko", "Pat Ivers", "Bobbie Oliver", 
             "Merrill Wagner", "Pat Tavenner", "May Wilson", "Candida Alvarez", 
             "Leslie Lalehzar", "Pat Walsh", "Francesca Jones", "Avital Oz", "Jody Sperling", 
             "Robin Bruch", "Robin Lee Crutchfield", "Dee Axelrod", "Lilly Brody",
             "Jody Culkin", "A. Kynn Forgach", "Tonie Roos", "Isolde Wawrin",
             "Avital Oz", "Toby MacLennan", "Paulette Nenner", "Pooh Kaye", "Pat Place",
             "Robin Tewes", "Anna Bisso", "Jeanie Black", "Marlene Bloomer", 
             "Leslie Eve Child", "Robin Holder", "Catti (Catherine James)", "Kris Waneck",
             "Lynn Swanson", "Kieko Bonk", "Jessie Benton-Evans-Gray", "Pene Bonita", 
             "Josely Carvalho", "Sydney Blum", "Danita Geltner", "Tomiyo Sasaki", 
             "Tuija Lindstrom", "Merian Soto", "Katrini Krinsky", "C. Ann Carter",
             "Jerri Allyn", "Mierle Laderman Ukeles", "Adrienne Farb", "Renee Rockoff",
             "Muna Tseng", "Sabra Moore", "Vernita Nemec", "Hedy O'Beil",
             "Rhea Sanders", "Katheryn Anne Sins", "Selina Trieff", "Suruchi Chand",
             "Jean Gallagher", "Faithanne Carapella", "Ora Lerman", "Janice Becker",
             "Merrill Wagner", "Mierle Laderman Ukeles", "Lori Beth Blaikie", 
             "Penny Coleman", "Nanue Lelue", "Moira Sina", "Robyn Almaleh", "Margot Lovejoy",
             "Serena Bocchino", "Merrin Eirth", "Geraldine Erman", "Roxanne Blanchard",
             "Liadin Cooke", "Mirjam de Zeeuw", "L. Brandon Krall", "Antonella Piemontese",
             "Daina Shobrys", "Esperanza Cortes", "Kay Miller", "Solfrid Mortensen",
             "Robin Stanaway", "Lynn Wilder", "Anna Plotnicka", "Andromahi Kefalos",
             "Hillary Leone", "Katharina Karrenberg", "Dara Silverman", "Tatyana Gubash",
             "Buffie Johnson", "Margrit Lewczuk", "L.C. Armstrong", "Yvette Helin",
             "Zaporah Jacobs", "Lanie Lee", "Marijke van Warmerdam", "Candida Alvarez",
             "Rise Cale", "Juliane Duda", "Gunda Foerster", "Ursula Kraft", "Merrill Wagner",
             "Edy Ferguson", "Liza May Post", "Juana Valdes", "Xinping Wang", 
             "Mandy Ming-Yin Yim", "Fabiana de Barros", "Juliet Lea", "Rekha Rodwittiya",
             "Alma Suljevic", "Adriana Varejão", "Celeste Boursier-Mougenot", "Ciara Finnegan",
             "Jean van Heeswijk", "Adriana Arenas", "Tracey Baran", "Chakaia Booker", 
             "Alix Lambert", "Jyung Mee Park", "Tamara Grcic", "Raffaella Nappo", 
             "Sabrina Mezzagui", "Safy Etiel", "Kaffe Matthews", "Ivana Franke", "Oladélé Bamgboyé", 
             "Sophia Al Maria", "Fatima Al Qadiri", "Amal Khalaf", "Samara Golden",
             "Amal Kenawy", "Jillian Mayer", "Carole Alden", "Tameca Cole", "Amber Rose Daniel",
             "Nereida García-Ferraz", "Chandra McCormick", "Cedar Mortenson", "Rowan Renee",
             "Treacy Ziegler", "Elysia Chuquimia Crampton", "Charisse Pearlina Weston", 
             "Glenda Hydler", "Yeohlee Teng", "Kei Takei", "Su-Mei Tse", "Katrín Sigurdardóttir", 
             "Rania Stephan", "Saya Woolfalk", "Frieda Toranzo Jaeger", "Whitney Claflin", 
             "Amanda Fielding", "Valborg Fletre Linn", "Buffie Johnson", "Yoshie Ueki", 
             "Anna Oppermann", "Miri Segal", "Aïda Ruilova", "Libby McInnis", 
             "Isca Greenfield-Sanders", "Misaki Kawai", "Zackary Drucker", "Sascha Braunig",
             "Iiu Susiraja", "Leslie Martinez", "Jasmine Gregory")

onepoint03 <- c("Yuki Hartman", "Myrel Chernick", "Gillian Bradshaw-Smith", 
                "Elizebeth Egbert", "Vita Giorgi", "Madelon Jones", "Robin Lehrer", 
                "Dee Shapiro", "Arlene Slavin", "Ilise Greenstein", "Laurace James", 
                "Clover Vail", "Hass Murphy", "Merrill Wagner", "Frankie Mann", 
                "A. Kimberlin Blackburn", "Janita Geltner", "Rae Berolzheimer", 
                "Blondell Cummings", "Toby MacLennan", "Lyne Lapointe", "Helina Hughes",
                "Cookie Mueller", "Rii Kanzaki", "Tomiyo Sasaki", "Birgitta Liljebladh",
                "Tonie Roos", "Hannan Ashrawi", "Luce Irigaray", "Su Friedrich",
                "Chick Strand", "Ame Gilbert", "Robin Holder", "Catti (Catherine James)",
                "Lynn Klosky", "Leslie-Jane Pessemier", "Lynn Swanson", "Marion Gray",
                "Rae Langston", "Su-Chen Hung", "Pene Bonita", "Bisa Washington", 
                "Leslie Sharpe", "Lynn McCary", "Danita Geltner", "Aki Fujiyoshi", 
                "Aki Onda", "Anna Gabriel", "Liadin Cooke", "Mo White", "Beck Underwood",
                "Claude Wampler", "Anna Conway", "Anna Craycoft", "Alexis Hunter", 
                "Lole de Freitas", "Anna Keier", "Marijke van Warmerdam", "Dora Budor", 
                "Tolia Astakhishvili", "Geumhyung Jeong", "Ser Serpas", "Pat Oleszko", 
                "Pat Ivers", "Bobbie Oliver", "Merrill Wagner", "Pat Tavenner", "May Wilson",
                "Candida Alvarez", "Leslie Lalehzar", "Pat Walsh", "Jamillah Jennings",
                "Francesca Jones", "Avital Oz", "Jody Sperling", "Gioia Timpanelli",
                "Inge Mahn", "Alba Cane", "Jody Culkin", "Paulette Nenner", "Toni Morrison", 
                "Anna Mariani", "Polly Kiesel", "Lynn Robinson", "Camilla Warenskjold-Dybvik",
                "Daina Shobrys", "Esperanza Cortes", "Kay Miller", "Solfrid Mortensen", 
                "Anna Plotnicka", "Hillary Leone", "Tatyana Gubash", "Buffie Johnson", 
                "Margrit Lewczuk", "L.C. Armstrong", "Yvette Helin", "Zaporah Jacobs", 
                "Lanie Lee", "Candida Alvarez", "Juliane Duda", "Gunda Foerster", 
                "Ursula Kraft", "Edy Ferguson", "Liza May Post", "Juana Valdes",
                "Xinping Wang", "Mandy Ming-Yin Yim", "Fabiana de Barros", "Juliet Lea",
                "Rekha Rodwittiya", "Alma Suljevic", "Adriana Varejão", "Ciara Finnegan",
                "Adriana Arenas", "Tracey Baran", "Chakaia Booker", "Alix Lambert", 
                "Jyung Mee Park", "Tamara Grcic", "Raffaella Nappo", "Sabrina Mezzagui",
                "Safy Etiel", "Adrianna Sa", "Carola Dertnig", "Ivana Franke",
                "Midori Araki", "Hanako Kunishi", "Hitomi Uchikura", "Yuka Wake",
                "Amanda Forbis", "Alexandra Korejwo", "Liane Lang", "Lucretia Knapp", 
                "Eline McGeorge", "Jeanine Oleson", "Jessie Shefrin", "Ottonella Mocellin", 
                "Valerie Prot", "Amanda Ralph", "Constanze Schweiger", "Katleen Vermeir",
                "Petra Lindholm", "Dianna Frid", "Kira Lynn Harris", "Xiuwen Cui", "Sungmi Lee",
                "Lisi Raskin", "Felisa Funes", "Meredyth Sparks", "McKendree Key",
                "Senam Okudzeto", "Tomoko Takahashi", "Margie Strosser", "Tamara Gonzales",
                "Prema Murthy", "Rä di Martino", "Amalia Mesa-Bains", "Shizuka Yokomizo",
                "Carey Young", "Vinca Kruk")



Full_PS1 <- Full_PS1 |>
  mutate(GenderConf3 = case_when(
    Gender == "female" ~ 1,
    Gender == "male" ~ 0, 
    Full_PS1$artistName %in%  point03 ~ 0,
    Full_PS1$artistName %in%  point23 ~ 0.2,
    Full_PS1$artistName %in%  point53 ~ 0.5,
    Full_PS1$artistName %in%  point83 ~ 0.8,
    Full_PS1$artistName %in%  onepoint03 ~ 1, 
    TRUE ~ 0.5
  ))


# average the three, split into gender from there

for(i in 1:nrow(Full_PS1)) {
  if ((Full_PS1$GenderConf1[i] + Full_PS1$GenderConf2[i] + Full_PS1$GenderConf3[i])/3 >= 0.65) {
    Full_PS1$Gender[i] <- "female"
  } else if ((Full_PS1$GenderConf1[i] + Full_PS1$GenderConf2[i] + Full_PS1$GenderConf3[i])/3 <= 0.35) {
    Full_PS1$Gender[i] <- "male"
  } else {
    Full_PS1$Gender[i] <- "unknown/other"
  }
}

# add avg as variable in df

Full_PS1 <- Full_PS1 |> 
  mutate(AvgGenderConf = (GenderConf1 + Full_PS1$GenderConf2 + Full_PS1$GenderConf3)/3)

# down to 300 unknown

save(Full_PS1, file = "Full_PS1.Robj")
write.csv(Full_PS1, "Full_PS1.csv", row.names = FALSE)

PS1_Artists <- PS1_Artists |>
  select(artistName, artistNationality, artistYOB, artistYOD) |>
  left_join(Full_PS1 |>
              select(artistName, Gender, AvgGenderConf), by = "artistName")

PS1_Artists <- PS1_Artists[!duplicated(PS1_Artists), ]


save(PS1_Artists, file = "PS1_Artists.Robj")
